//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhóm4_SHOOS_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDH
    {
        public int MACTDH { get; set; }
        public Nullable<int> MADH { get; set; }
        public Nullable<int> MASP { get; set; }
        public Nullable<int> SL { get; set; }
    
        public virtual DATHANG DATHANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
