//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhóm4_SHOOS_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DATHANG()
        {
            this.CHITIETDHs = new HashSet<CHITIETDH>();
        }
    
        public int MADH { get; set; }
        public Nullable<int> MAKH { get; set; }
        public Nullable<int> MAKM { get; set; }
        public Nullable<int> MAGH { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public string GHICHU { get; set; }
        public Nullable<int> TONGTIEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDH> CHITIETDHs { get; set; }
        public virtual GIAOHANG GIAOHANG { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
    }
}
