//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhóm4_SHOOS_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETDHs = new HashSet<CHITIETDH>();
        }
    
        public int MASP { get; set; }
        public string TENSP { get; set; }
        public Nullable<int> MATH { get; set; }
        public Nullable<int> MANCC { get; set; }
        public string MAUSAC { get; set; }
        public Nullable<int> KICHCO { get; set; }
        public Nullable<int> SL { get; set; }
        public string MOTA { get; set; }
        public string HINH { get; set; }
        public Nullable<int> GIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDH> CHITIETDHs { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual THUONGHIEU THUONGHIEU { get; set; }
    }
}
