//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhóm4_SHOOS_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHTOAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THANHTOAN()
        {
            this.GIAOHANGs = new HashSet<GIAOHANG>();
        }
    
        public int MATT { get; set; }
        public Nullable<int> MAHD { get; set; }
        public Nullable<int> MATHE { get; set; }
        public Nullable<System.DateTime> NGAYTHANHTOAN { get; set; }
        public Nullable<int> SOTIEN { get; set; }
        public string HINHTHUCTHANHTOAN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIAOHANG> GIAOHANGs { get; set; }
        public virtual HOADON HOADON { get; set; }
        public virtual THE THE { get; set; }
    }
}
